### ISSUE TITLE
Missing G28

### ISSUE THREAD

**Issue by stonegear** [Caribou3d/CaribouDuet-Configuration-and-Macros#3]
Missing the G28 at the beginning. 
Please correct this @wschadow 

https://github.com/Caribou3d/CaribouDuet2Wifi-ConfigurationMacros/blob/9829710f6267ebd0af026922a54eac6a015afba7/Configuration/SlicerScripts/StartScripts/PrusaSlicer-StartScript#L7

**Comment by wschadow** [comment]
When a print is started first bed.g is executed, then all gcode from slicer comes in. In bed.g you'll find the homing.
